#!/bin/sh
[ -n "$IPKG_INSTROOT" ] && exit 0

. /lib/functions.sh

gid="$(group_add_next hiddify)"
user_exists hiddify || user_add hiddify "" "$gid" hiddify /etc/hiddify /bin/false

mkdir -p /etc/hiddify
chown -R hiddify:hiddify /etc/hiddify
chmod 750 /etc/hiddify

/etc/init.d/hiddify enable
rm -rf /tmp/luci-indexcache* /tmp/luci-modulecache
/etc/init.d/rpcd restart
# an upgrade runs the old prerm (stop) first; bring the proxy back so Passwall2 keeps working
[ "$(uci -q get hiddify.main.enabled)" = 1 ] && /etc/init.d/hiddify start
exit 0
